### PR TITLE
fix(interceptor): export auth interceptor in index.ts

### PR DESCRIPTION
**Pull request by rohitkrai03**

### CODE REVIEW

**Comment by rohitkrai03** [comment]
@joshuawilson For some reason https://www.npmjs.com/package/ngx-login-client/v/1.4.5 doesn't contains code for auth interceptor. I guess it was not released properly. Can you merge this and do a manual release for 1.x version?

**Comment by rohitkrai03** [comment]
Thanks @joshuawilson

**Comment by rohitkrai03** [comment]
@joshuawilson The 1.4.6 release has the directory structure all messed up. Even the index.js is not there in the root directory.

**Comment by joshuawilson** [comment]
let's get everything upgraded and this should sort it's self out

**Pull request merged**
