### PR TITLE
add a piepline to update downstream dependencies

### PR DESCRIPTION
**Pull request by rawlingsj**
This is an initial attempt and automating the update of downstream npm package.json files using github pull requests so that CI for each project runs on the newly released version.

Once this merges we should see a job appear on http://jenkins.cd.k8s.fabric8.io/job/fabric8-cd/.  

For now this pipeline will:
- require a manual trigger once a release has finished on centosci, we can automate this later with polling or webhooks
- get the latest release version using the git tag from this repo
- clone `fabric8-ui/ngx-fabric8-wit`& `fabric8io/fabric8-ui`
- checkout a new versionupdate branch
- update the package.json with the latest release version of `ngx-login-client` using the git tag form above
- commit & push
- make a github pull requests to master
- wait for CI to run and the PR's to merge

This is an initial attempt, if it works as planned we can duplicate the Jenkinsfile into other repos and simply update the downstream projects they need to update.  https://github.com/rawlingsj/ngx-login-client/blob/master/Jenkinsfile#L15-L16

After this we can also look to trigger the release in centosci for those downstream projects or update their Jenkinsfiles to perform the npm build + docker push themselves like the other fabric8 projects.  But this is just a start and aimed to be a quick win to avoid manual updates of package.json files.

CC @joshuawilson

### CODE REVIEW

**Comment by rawlingsj** [comment]
@joshuawilson @pmuir @jstrachan not sure how strict we are with self merges on this repo so I'll be patient.  However it would be good to get this merged so we can try it out and see what happens :)

**Comment by joshuawilson** [comment]
@rawlingsj Will this try to auto update or send a PR to fabric8-ui? if so we may want to try this out on ngx-widgets. We are not ready to use the latest release in fabric8-ui right now. It builds but the UI doesn't work.

**Comment by rawlingsj** [comment]
@joshuawilson it will send a Pull Request, so if CI fails on fabric8-ui OR an approver decides to reject the PR it then the update will not happen.  

I think it would still be good to merge this PR so we can verify the scenario so everyone can see, WDYT?

**Comment by rawlingsj** [comment]
YAY 
http://jenkins.cd.k8s.fabric8.io/job/fabric8-ui/job/ngx-login-client/job/master/
and yay
https://github.com/fabric8io/fabric8-ui/pull/250

OK so we can remove the merge comment but I think that's a good start @joshuawilson?

**Comment by rawlingsj** [comment]
Automation + Jenkins pipelines FTW :)

**Comment by kbsingh** [comment]
can the content at http://jenkins.cd.k8s.fabric8.io/job/fabric8-ui/job/ngx-login-client/job/master/ be made public ?

**Comment by joshuawilson** [comment]
@kbsingh who owns that? I'm guessing that is @rawlingsj or @jstrachan

**Pull request merged**
